name: Check Markdown links

on: 
  workflow_dispatch:
  push:
  schedule:
  # Run every Monday at 9:00 AM
  - cron: "0 9 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        folder-path: 'content/docs'
